accordion:
  controls: arrow # arrow | plus-minus
  copyButton:
    ariaLabel: Copy page section link to clipboard
    successText: Copied page section link to clipboard
    symbol: §
  globalControls:
    collapseText: Collapse All
    expandText: Expand All

analytics:
  googleId: ''

bylineFormat: name-title # name | name-title | false

bibliography:
  displayOnPage: true
  displayShort: true
  heading: Bibliography

citations:
  divider: ', '
  popupStyle: text # text | icon

entryPage:
  sideBySide: false
  objectLinkText: View in Collection

epub:
  defaultCoverImage: 'epub-cover.png'
  outputDir: '_epub'

footnotes:
  backlinkSymbol: '↩'

figures:
  assetDir: '/_assets/'
  enableModal: true
  imageDir: '/_assets/images'

licenseIcons: true

localization:
  defaultLocale: en-us

menuType: full # full | brief

navigation:
  nextButtonText: Next
  prevButtonText: Back

pageTitle:
  labelDivider: '. '

pdf:
  filename: 'publication'
  outputDir: '/_assets/downloads' 
  pagePDF:
    accessLinks:
      - header: true 
        label: 'PDF'
      - footer: true
        label: 'Download this page'
    coverPage: true
    output: false
  publicationPDF:
    output: true

ref:
  sequenceTransition: 30

searchEnabled: true

tableOfContents:
  contributorDivider: ' — '
